# Generated by Django 4.1 on 2022-08-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkGroupCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=255)),
                ('last_user_id', models.IntegerField(null=True)),
                ('last_page', models.IntegerField(null=True)),
                ('count_save_photo', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'vk_group_counter',
            },
        ),
    ]
