# Generated by Django 4.1 on 2022-08-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=255, unique=True)),
                ('group_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vk_group',
            },
        ),
        migrations.CreateModel(
            name='VkUserRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('photo_url', models.URLField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('saved', models.BooleanField(default=False)),
                ('checked', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse.vkgroup')),
            ],
            options={
                'db_table': 'vk_user_rawdata',
            },
        ),
    ]
