# Generated by Django 4.1 on 2022-08-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vkuserrawdata',
            name='photo_url',
        ),
    ]
