# Generated by Django 4.1 on 2022-08-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkgroupcounter',
            name='group_name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
