# Generated by Django 4.1 on 2022-08-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0002_remove_vkuserrawdata_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuserrawdata',
            name='photo_100',
            field=models.URLField(default='sa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vkuserrawdata',
            name='photo_200',
            field=models.URLField(default='sa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vkuserrawdata',
            name='photo_400',
            field=models.URLField(default='sa'),
            preserve_default=False,
        ),
    ]
