# Generated by Django 4.1 on 2022-08-29 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0003_vkuserrawdata_photo_100_vkuserrawdata_photo_200_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vkuserrawdata',
            name='photo_100',
        ),
        migrations.RemoveField(
            model_name='vkuserrawdata',
            name='photo_200',
        ),
    ]
