# Generated by Django 4.1 on 2022-09-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0004_remove_vkuserrawdata_photo_100_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vkuserrawdata',
            old_name='photo_400',
            new_name='photo',
        ),
    ]
