# Generated by Django 4.1 on 2022-09-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0005_rename_photo_400_vkuserrawdata_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VkUserRawData',
        ),
    ]
