# Generated by Django 4.1 on 2022-08-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, unique=True)),
                ('last_name', models.CharField(max_length=255, unique=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=255)),
            ],
            options={
                'db_table': 'user_name',
            },
        ),
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_100', models.ImageField(upload_to='images/photo_100/')),
                ('photo_200', models.ImageField(upload_to='images/photo_200/')),
                ('photo_400', models.ImageField(upload_to='images/photo_400/')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=255)),
            ],
            options={
                'db_table': 'user_photo',
            },
        ),
    ]
