# Generated by Django 4.1 on 2022-08-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='first_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='username',
            name='last_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
