# Generated by Django 4.1 on 2022-08-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_username_first_name_alter_username_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='localization',
            field=models.CharField(default='1', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='username',
            name='patronymic',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
