# Generated by Django 4.1 on 2022-09-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_username_localization_username_patronymic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphoto',
            name='photo_400',
        ),
        migrations.AddField(
            model_name='userphoto',
            name='photo',
            field=models.ImageField(default='a', upload_to='images/photo/'),
            preserve_default=False,
        ),
    ]
