# Generated by Django 4.1 on 2022-09-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_userphoto_photo_400_userphoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphoto',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=7, null=True),
        ),
    ]
