# Generated by Django 4.1 on 2022-09-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userphoto_age_alter_userphoto_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='gender',
            field=models.CharField(choices=[('man', 'man'), ('woman', 'woman')], max_length=255),
        ),
        migrations.AlterField(
            model_name='username',
            name='localization',
            field=models.CharField(choices=[('ru', 'ru'), ('eng', 'eng')], max_length=40),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='gender',
            field=models.CharField(choices=[('man', 'man'), ('woman', 'woman')], max_length=7, null=True),
        ),
    ]
